// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "KITech Unternehmensinformationen",
  description: "Liefert einen \xDCberblick \xFCber die KITech Software UG: Kernkompetenzen, Standort, Gesch\xE4ftsf\xFChrung und Positionierung im Markt.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "KITech Software UG (haftungsbeschr\xE4nkt)",
            founded: 2023,
            managingDirector: "Ayham Alkhalil",
            location: "Wedekindstra\xDFe 14, 30161 Hannover, Deutschland",
            website: "https://kitech-software.de",
            positioning: "KI mit ROI-Garantie f\xFCr den deutschen Mittelstand. DSGVO-konforme, auditierbare KI-Systeme \u2013 Made in Germany.",
            coreCompetencies: [
              "KI-Audit & Potenzialanalyse",
              "Custom LLM-Integrationen (RAG, Fine-Tuning, EU-Deployment)",
              "Computer Vision (Qualit\xE4tskontrolle, OCR, Edge-Deployment)",
              "Intelligente Assistenten & Chatbots",
              "Datenplattform-Aufbau (DWH, ETL, Analytics)",
              "MLOps & Wartung"
            ],
            differentiators: [
              "Kein Vendor Lock-in \u2013 Kunde besitzt seinen Code",
              "DSGVO-konforme Architektur",
              "Hosting in Deutschland/EU m\xF6glich",
              "Produktivsysteme statt Demo-Effekte",
              "ROI-Garantie: kein Erfolg, keine Zahlung"
            ],
            registration: "HRB 230077 (Amtsgericht Hannover)",
            vatId: "DE459778632"
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/get-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var SERVICES = [
  {
    slug: "ki-audit",
    name: "KI-Audit & Potenzialanalyse",
    summary: "Objektive Bewertung der KI-Reife. Datenqualit\xE4t, Prozesseignung, Machbarkeit, ROI-Kalkulation."
  },
  {
    slug: "custom-llm",
    name: "Custom LLM-Integrationen",
    summary: "Ma\xDFgeschneiderte Sprachmodell-L\xF6sungen mit RAG, Fine-Tuning, EU-/On-Prem-Deployment."
  },
  {
    slug: "computer-vision",
    name: "Computer Vision",
    summary: "Bilderkennung f\xFCr Qualit\xE4tskontrolle, OCR, Objekterkennung, Edge-Deployment (<100ms)."
  },
  {
    slug: "assistenten",
    name: "Intelligente Assistenten",
    summary: "KI-Chatbots und Wissensassistenten f\xFCr Kundenservice und interne Prozesse."
  },
  {
    slug: "datenplattform",
    name: "Datenplattform-Aufbau",
    summary: "Data Warehousing, ETL-Pipelines, Datenqualit\xE4tsmanagement, Analytics-Dashboards."
  },
  {
    slug: "mlops",
    name: "MLOps & Wartung",
    summary: "Modell-Monitoring, automatisiertes Retraining, Performance-Optimierung, 24/7 Support."
  }
];
var get_services_default = defineTool2({
  name: "get_services",
  title: "KITech Leistungen",
  description: "Liste aller Leistungen und Beratungsangebote von KITech Software. Optional nach Slug filterbar.",
  inputSchema: {
    slug: z.string().optional().describe(
      "Optionaler Slug einer einzelnen Leistung (z. B. 'ki-audit', 'custom-llm', 'computer-vision')."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const data = slug ? SERVICES.filter((s) => s.slug === slug) : SERVICES;
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }]
    };
  }
});

// src/lib/mcp/tools/get-case-studies.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var CASE_STUDIES = [
  {
    industry: "Immobilien / Bauunternehmen",
    problem: "Manuelle Zuordnung von Zahlungen zu Mietvertr\xE4gen",
    solution: "Datenbank mit intelligenter Zuordnung",
    result: "50% Zeitersparnis bei voller Entlastung der Partner"
  },
  {
    industry: "Consulting / Zertifizierungsgesellschaft",
    problem: "Chaotische Terminverwaltung",
    solution: "CRM- und Auditsystem mit Outlook-Kalender-Schnittstelle",
    result: "40% Zeitersparnis, saubere \xDCbersicht kritischer Themen"
  },
  {
    industry: "Handwerk / Glasbau",
    problem: "Ineffiziente Auftragsverarbeitung",
    solution: "Automatisierte Angebots- und Rechnungserstellung",
    result: "70% k\xFCrzerer Verkaufsprozess"
  }
];
var get_case_studies_default = defineTool3({
  name: "get_case_studies",
  title: "KITech Case Studies",
  description: "Referenzprojekte von KITech Software mit Problem, L\xF6sung und messbarem Ergebnis.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CASE_STUDIES, null, 2) }]
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "KITech Kontakt",
  description: "Kontaktinformationen von KITech Software inkl. E-Mail, Telefon, Adresse und Terminbuchungslink.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            email: "info@kitech-software.de",
            phone: "+49 (0) 511 89738590",
            address: "Wedekindstra\xDFe 14, 30161 Hannover, Deutschland",
            website: "https://kitech-software.de",
            booking: "https://calendly.com/automatisieren-mit-kitech/30min",
            managingDirector: "Ayham Alkhalil"
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kitech-software-mcp",
  title: "KITech Software MCP",
  version: "0.1.0",
  instructions: "\xD6ffentlicher MCP-Server der KITech Software UG (Hannover, Deutschland). Liefert strukturierte Informationen zu Unternehmen, Leistungen, Referenzprojekten und Kontaktdaten. Nutze get_company_info f\xFCr \xDCberblick, get_services f\xFCr Beratungs- und Entwicklungsleistungen, get_case_studies f\xFCr Referenzen und get_contact f\xFCr Kontakt- und Buchungsdaten.",
  tools: [get_company_info_default, get_services_default, get_case_studies_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
